# docker-compose.yml
version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    service: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    service: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - logging_network
    depends_on:
      - opensearch

  # fluentd:
  #   build: 
  #     context: ./fluentd
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./fluentd/conf:/fluentd/etc
  #     - fluentd_buffer:/fluentd/log/buffer
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #   networks:
  #     - logging_network
  #   depends_on:
  #     - opensearch

networks:
  logging_network:
    external: true    # Change this to external

volumes:
  opensearch_data: 
  # fluentd_buffer: