# docker-compose.yml
version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=false"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "OPENSEARCH_SECURITY_SSL_ONLY=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Mickey89c51!"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=false"
      - "OPENSEARCH_USERNAME=admin"
      - "OPENSEARCH_PASSWORD=Mickey89c51!"
      - "OPENSEARCH_SSL_VERIFICATION_MODE=none"
    networks:
      - logging_network
    depends_on:
      - opensearch

networks:
  logging_network:
    external: true    # Change this to external

volumes:
  opensearch_data: 